name: 'Checkov SAST Scan'
description: 'Runs a Checkov scan on source code using central policies.'

inputs:
  path:
    description: 'The path to the directory to scan.'
    required: false
    default: '.'
  version-tag:
    description: 'The git ref of the central policies repo to use.'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Checkout custom policies
      uses: actions/checkout@v4
      with:
        repository: 'UKHomeOffice/core-cloud-workflow-checkov-sast-scan'
        ref: ${{ inputs.version-tag }}
        path: 'checkout-central-checkov-policies'

    - name: Move policies
      shell: bash
      run: |
        mkdir -p central-checkov-policies
        mv checkout-central-checkov-policies/central-checkov-policies central-checkov-policies

    - name: Run Checkov Scan
      id: checkov_scan
      uses: bridgecrewio/checkov-action@v12
      with:
        output_format: cli,sarif
        quiet: true
        soft_fail: true
        directory: ${{ inputs.path }}
        output_file_path: results.sarif
        external_checks_dirs: central-checkov-policies
        skip_check: CKV_CCL_CUSTOM_001,CKV_CCL_CUSTOM_002
        download_external_modules: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'results.sarif'
        category: 'checkov-sast-scan'
