name: 'Checkov Scan'
description: 'A Checkov scan using centrally-stored custom policies'

inputs:
  deploy-key:
    description: 'The SSH deploy key for checking out the custom policies repo.'
    required: true
  known-hosts:
    description: 'The known_hosts entry for the GHES instance.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure SSH Known Hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.known-hosts }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
      shell: bash

    - name: Checkout custom policies repository
      uses: actions/checkout@v4
      with:
        repository: 'UKHomeOffice/core-cloud-workflow-checkov-sast-scan'
        ref: 'composite-action'
        path: 'central-checkov-policies'
        ssh-key: ${{ inputs.deploy-key }}

    - name: Run Checkov Scan
      id: checkov_scan
      uses: bridgecrewio/checkov-action@v12
      with:
        output_format: cli,sarif
        quiet: true
        soft_fail: true
        directory: '.'
        output_file_path: results.sarif
        external_checks_dirs: central-checkov-policies

    - name: Upload SARIF file
      if: ${{ success() || failure() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'results.sarif'
        category: 'checkov-scan'
