# This workflow is for scanning your Terraform Plan file/s and Source Code with Checkov
# Environment variables are currently used instead of a Checkov config file as all options are available and it saves having to add additional steps for checking out the repo with a token.
# https://github.com/bridgecrewio/checkov-action/blob/master/action.yml

name: Checkov Reusable Scan

on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string
      path:
        required: false
        type: string
    secrets:
      account_id:
        required: false

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov Scan
        id: checkov_scan
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          quiet: true
          # Enabling soft_fail temporarily for easier adoption. Once repos are compliant, remove this and use skip_check or soft_fail_on containing the global suppression list agreed by the SWG.
          soft_fail: true
          # Use skip_check if we don't want the check to appear in the console.
          # Use soft_fail_on when we want to make the suppressed check known e.g. for future mitigation.
          # skip_check: CKV_AWS_EXAMPLE1,CKV_AWS_EXAMPLE2
          # soft_fail_on: CKV_AWS_EXAMPLE1,CKV_AWS_EXAMPLE2
          directory: '.'
          output_file_path: results.sarif
          external_checks_dirs: checkov-policies

      - name: Upload SARIF file (Source Code)
        if: ${{ success() || failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'results.sarif'
          category: 'checkov-scan' 
