name: Checkov and Sonarqube Scans
 
on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      sonar_host_url:
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

jobs:
  checkov-scan:
    uses: UKHomeOffice/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-base.yaml@1.7.0

  sonarqube-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Tests & Generate Coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          python -m pytest tests/ --cov=scripts --cov-report=xml

      - name: Sonarqube Composite Action
        uses: UKHomeOffice/core-cloud-workflow-sonarqube-scan@1.1.7
        with:
          sonar_token: ${{ secrets.sonar_token }}
          sonar_host_url: ${{ secrets.sonar_host_url }}
