name: Sync with GHES Instance

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-live-ops-tooling:
    name: Sync to live-ops-tooling GHES instance
    uses: UKHomeOffice/core-cloud-workflows-actions-sync/.github/workflows/sync_hub.yaml@sync-branch
    with:
      ghes-instance-url: 'https://github.cc-live-ops-tooling.core.homeoffice.gov.uk'
      ghes-owner: 'home-office-sandbox'
      environment: 'live-ops-tooling'
    secrets: inherit
  sync-test-ops-tooling:
    name: Sync to test-ops-tooling GHES instance
    uses: UKHomeOffice/core-cloud-workflows-actions-sync/.github/workflows/sync_hub.yaml@sync-branch
    with:
      ghes-instance-url: 'https://github.cc-test-ops-tooling.np.core.homeoffice.gov.uk'
      ghes-owner: 'Home-Office-Test'
      environment: 'test-ops-tooling'
    secrets: inherit
