name: Sync with GHES Instance

on:
  push:
    branches:
      - reusable-workflows-sync
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-with-hub:
    uses: UKHomeOffice/core-cloud-workflows-actions-sync/.github/workflows/sync_hub.yaml@sync-branch
    with:
      ghes-instances: |
        https://github.cc-live-ops-tooling.core.homeoffice.gov.uk
      ghes-owner: |
        home-office-sandbox
    secrets:
      APP_ID: ${{ secrets.GHES_APP_ID }}
      PRIVATE_KEY: ${{ secrets.GHES_PRIVATE_KEY }}
